#!/bin/bash

DELAY=$((60 + RANDOM%10)) # exponential backoff + jitter, to avoid multiple exp. backoffs from firing at the same time. set delay to 60 because gcloud quotas are enforced on minute increments.
while true; do
	PIPE=$(mktemp -u)
	mkfifo $PIPE
	exec 3<>$PIPE 4<$PIPE
	rm $PIPE

	if [ $DELAY -gt 320 ]; then
		echo "gcloud operation cannot be completed due to quota limit" >&2
		exit 5
	fi
	if gcloud $@ 2> >(tee -a /dev/stderr >&3); then
		exit 0
	else
		RC=$?
		exec 3>&-
		grep -q "Quota exceeded" <&4 && sleep $DELAY || exit $RC
		((DELAY *= 2))
	fi
done
