#!/bin/bash

DELAY=10
while true; do
	PIPE=$(mktemp -u)
	mkfifo $PIPE
	exec 3<>$PIPE 4<$PIPE
	rm $PIPE

	if [ $DELAY -gt 320 ]; then
		echo "gcloud operation cannot be completed due to quota limit" >&2
		exit 5
	fi
	if gcloud $@ 2> >(tee /dev/stderr >&3); then
		exit 0
	else
		RC=$?
		exec 3>&-
		grep -q "Quota exceeded" <&4 && sleep $DELAY || exit $RC
		((DELAY *= 2))
	fi
done
