#!/bin/bash

# add gcloud credentials to slurm's home directory
[ ! -d ~slurm/.config/gcloud ] && mkdir -p ~slurm/.config/gcloud

# Source the credentials, preferring Secret Manager over the NFS copy.
#
# Secret Manager is the path that survives the NFS mount going away
# (NFS-FUSE-IMPLEMENTATION-PLAN.md section 2.6). canine publishes the secret and
# passes its name to workers as the credentials-secret instance metadata
# attribute (slurm_resume.py).
#
# This is the one call that must authenticate as the *service account*: the
# user credentials it is fetching do not exist on this node yet. That is also
# why CLOUDSDK_CONFIG must be unset here -- the image points it at
# /user_gcloud_config, which does not exist until a few lines below, and
# pointing gcloud at a nonexistent config dir breaks metadata-server auth.
fetch_credentials_from_secret_manager() {
	local secret
	secret=$(curl -s -f -H "Metadata-Flavor: Google" \
	  "http://metadata.google.internal/computeMetadata/v1/instance/attributes/credentials-secret" \
	  2>/dev/null) || return 1
	[ -z "$secret" ] && return 1

	echo "Fetching gcloud credentials from Secret Manager secret ${secret} ..."
	local tgz; tgz=$(mktemp /tmp/adc.XXXXXX.tgz)
	if ! ( unset CLOUDSDK_CONFIG; gcloud secrets versions access latest \
	         --secret="$secret" --format='get(payload.data)' 2>/dev/null \
	       | tr '_-' '/+' | base64 -d > "$tgz" ) || [ ! -s "$tgz" ]; then
		rm -f "$tgz"; return 1
	fi
	tar xzf "$tgz" -C ~slurm/.config/gcloud || { rm -f "$tgz"; return 1; }
	rm -f "$tgz"
	return 0
}

# Fall back to the NFS copy.
# exclude logs directory for copy, which can get huge.
# (although logs are explicitly not copied to the NFS from the controller when
#  the backend starts up, logs on the NFS get generated by the worker shutdown
#  script, which runs on the bare VM. [the command in the shutdown script is seemingly
#  immune to the concurrency issue that forces us to copy credentials in the first place])
fetch_credentials_from_nfs() {
	find /mnt/nfs/credentials/gcloud/ -mindepth 1 -maxdepth 1 ! -name "logs" \
	  -exec cp -r {} ~slurm/.config/gcloud \;
}

if fetch_credentials_from_secret_manager; then
	echo "Credentials sourced from Secret Manager."
else
	echo "Secret Manager credentials unavailable; falling back to the NFS copy." >&2
	fetch_credentials_from_nfs
fi

chown -R slurm:slurm ~slurm/.config/gcloud && \
  ln -s ~slurm/.config/gcloud /slurm_gcloud_config

# add gcloud credentials to user's home directory
HOMEDIR=`eval echo ~$HOST_USER`
[ ! -d $HOMEDIR/.config ] && mkdir -p $HOMEDIR/.config

cp -r ~slurm/.config/gcloud $HOMEDIR/.config/gcloud && \
  chown -R $HOST_USER:$HOST_USER $HOMEDIR/.config/ && \
  ln -s $HOMEDIR/.config/gcloud /user_gcloud_config

# add Docker credentials to user's home directory
[ ! -d $HOMEDIR/.docker ] && mkdir -p $HOMEDIR/.docker
ln -s /sgcpd/conf/docker_config.json $HOMEDIR/.docker/config.json
