#!/bin/bash

# add gcloud credentials to slurm's home directory
[ ! -d ~slurm/.config/gcloud ] && mkdir -p ~slurm/.config/gcloud

# copy gcloud credentials from NFS.
# exclude logs directory for copy, which can get huge.
# (although logs are explicitly not copied to the NFS from the controller when
#  the backend starts up, logs on the NFS get generated by the worker shutdown
#  script, which runs on the bare VM. [the command in the shutdown script is seemingly
#  immune to the concurrency issue that forces us to copy credentials in the first place])
find /mnt/nfs/credentials/gcloud/ -mindepth 1 -maxdepth 1 ! -name "logs" -exec cp -r {} ~slurm/.config/gcloud \; && \
  chown -R slurm:slurm ~slurm/.config/gcloud && \
  ln -s ~slurm/.config/gcloud /slurm_gcloud_config

# add gcloud credentials to user's home directory
HOMEDIR=`eval echo ~$HOST_USER`
[ ! -d $HOMEDIR/.config ] && mkdir -p $HOMEDIR/.config

cp -r ~slurm/.config/gcloud $HOMEDIR/.config/gcloud && \
  chown -R $HOST_USER:$HOST_USER $HOMEDIR/.config/ && \
  ln -s $HOMEDIR/.config/gcloud /user_gcloud_config

# add Docker credentials to user's home directory
[ ! -d $HOMEDIR/.docker ] && mkdir -p $HOMEDIR/.docker
ln -s /sgcpd/conf/docker_config.json $HOMEDIR/.docker/config.json
